---
title: "econometrics hw3"
output:
  html_document: default
  html_notebook: default
---




```{r}
# install.packages("foreign")
library(foreign)
getwd()
mlb1<-read.dta("C:/Users/warty/Documents/dsR/data/MLB1.DTA")
lnsalary<- log(mlb1$salary)
reg<- lm(lnsalary~years+gamesyr+bavg+hrunsyr+rbisyr+runsyr+fldperc+allstar+frstbase
         +scndbase+thrdbase+shrtstop+catcher,data=mlb1 )
summary(reg)
anova(reg)

reg11<-lm(lnsalary~frstbase+scndbase+thrdbase+shrtstop+catcher,data=mlb1)
summary(reg11)
```


question9

```{r}
w<-read.dta("C:/Users/warty/Documents/dsR/data/WAGE2.DTA")
lnwage<-log(w$wage)
reg1<-lm(lnwage~educ+exper+tenure+married+black+south+urban,data=w)
summary(reg1)
```





```{r}
exper2<-w$exper^2
tenure2<-w$tenure^2

reg2<-lm(lnwage~educ+exper+tenure+married+black+south+urban+exper2+tenure2,data=w)
summary(reg2)
anova(reg1,reg2)
```












































```{r}
reg3<-lm(lnwage~educ+exper+tenure+married+black+south+urban+black*educ,data=w)
summary(reg3)

```


```{r}
reg4<- lm(lnwage~educ+exper+tenure+married+black+south+urban+married*black,data=w) 
summary(reg4) 
```
